/*made by Miguel Rodrigues @ KBZ miguel.rodrigues@knowledgebiz.pt*/

//Signature for Email

module.exports = {
signature: '<table cellpadding="0" cellspacing="0" border="0" style="width: 500px;">'
    +'<tbody><tr>'
        +'<td style="padding-bottom: 10px;">'
            +'<table cellpadding="0" cellspacing="0" border="0">'
                +'<tbody><tr>'
                    +'<td style="padding-bottom: 10px;"><a href="www.vf-OS.eu"><img id="TemplateLogo" data-class="external" src="https://cd60f9d368cbcab0a50f-d3901811920f1cb10df2bd084d916385.ssl.cf1.rackcdn.com/2017/11/20/31d9f328c35842e7b4473d092f6c21b7.png" alt="vf-OS" style="display: block"></a></td>'
                +'</tr>'
                +'<tr>'
                    +'<td colspan="2" style="font-family: Arial; font-size: 14pt; color: rgb(51, 51, 51);">'
                        +'<font style="font-weight: bold; text-transform: uppercase; font-family: Arial; font-size: 14pt; color: rgb(51, 51, 51);">vf-OS Notification System</font>'
                    +'</td>'
                +'</tr>'               
            +'</tbody></table>'
         +'</td>'
    +'</tr>'
    +'<tr style="border-top: 2px solid #808080">'
        +'<td style="border-top: 2px solid #808080; padding-top: 10px; vertical-align: bottom;" align="right" valign="bottom">'
            +'<table cellpadding="0" cellspacing="0" border="0" style="padding-left: 40px">'
                +'<tbody><tr>'
                    +'<td>'
                        +'<a href="https://www.facebook.com/vfoseuropeanproject/">'
                            +'<img data-class="external" style="display: block" src="https://a8b03ffbc00ed4da54a1-0c6684360696717b63d89dbc0edb802c.ssl.cf1.rackcdn.com/icon-facebook_28x28.jpg">'
                        +'</a>'
                    +'</td>'                  
                    +'<td style="padding-left: 5px;">'
                        +'<a href="https://www.linkedin.com/in/vf-os-project/">'
                            +'<img data-class="external" style="display: block" src="https://a8b03ffbc00ed4da54a1-0c6684360696717b63d89dbc0edb802c.ssl.cf1.rackcdn.com/icon-linkedin_28x28.jpg">'
                        +'</a>'
                    +'</td>'
                +'</tr>'
            +'</tbody></table>'
        +'</td>'
    +'</tr>'
    +'<tr>'
        +'<td data-content="disclaimer" style="max-width: 500px; text-align: justify; padding-top: 10px; font-size: 8pt; color: rgb(136, 136, 136);" colspan="2">'
            +'<font style="font-family: Arial; font-size: 8pt; color: rgb(136, 136, 136);">You have received this email because you have been referred as a vf-OS user. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.</font>'
        +'</td>'
    +'</tr>'
+'</tbody></table><p style="color: rgb(136, 136, 136); font-family: Arial; font-size: 8pt; width: 500px;">'
+'</p>'
}